server:
  port: 8081

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

# publish all the metrics probability to zipkin (1.0 = 100%)
management:
  tracing:
    sampling:
      probability: 1.0
